### PR TITLE
Python scripts

### PR DESCRIPTION
**Pull request by zerox1212**
Added the scripts from the wiki.

Also added a custom script I tried to write, but I can't get it to work. Can someone review why require-optional-field.py doesn't work so I can fix it before merge?

### CODE REVIEW

**Comment by leehicks** [comment]
The "resource" is not there in user.register.post event. Try removing that and accessing first_name in payload directly.

**Comment by zerox1212** [comment]
In the wiki documentation the details around 'resource' isn't clear. What events have a resource and which don't?

**Comment by leehicks** [comment]
The "resource" wrapper is essentially used when arrays of things are passed in/out of the API, i.e. retrieving system resources like GET /api/v2/system/service. In places where there is a single entity involved, it is not typically used.

**Comment by zerox1212** [comment]
Does that mean payload is `string` ? Does the script need to parse it? When I tested this before I do not think payload is a native python type. Wiki makes it look like it should be a `dict`, but I don't think that's the case and I do not know how to debug this.

**Comment by zerox1212** [comment]
After some testing it seems that `payload` is a python class which contains attributes matching the fields?

The below is working.

``` python
payload = event.request.payload
if(payload):
    if payload.first_name == '':
        raise ValueError("First name missing")
```

I wish your clarification about resource was better explained in the wiki. I spent the last 2 days trying to make this script work. Thanks for the help.

**Comment by zerox1212** [comment]
I'm going to close this PR and make a new one as a single commit. I was working from the github website and didn't expect so many commits.

**Comment by leehicks** [comment]
For future reference, when I merge it, I can collapse it down to one.

On Sep 8, 2016 6:51 PM, "Andrew" notifications@github.com wrote:

Closed #1 https://github.com/dreamfactorysoftware/example-scripts/pull/1.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
https://github.com/dreamfactorysoftware/example-scripts/pull/1#event-783206821,
or mute the thread

**Pull request closed without merging**
